##
## This file is part of cq2rdf
##
## cq2rdf is free software: you can redistribute it and/or modify
## it under the terms of the GNU General Public License as published by
## the Free Software Foundation, either version 3 of the License, or
## (at your option) any later version.
##
## cq2rdf is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with cq2rdf.  If not, see <https://www.gnu.org/licenses/>.
##
name:                cq2rdf
version:             0.1.0
license:             GPL-3
author:              Konstantinos Lambrou-Latreille
maintainer:          klambroulatreille@cinematheque.qc.ca
copyright:           2020 Cinémathèque québécoise

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Gitlab at <https://gitlab.com/cinematheque-quebecoise/cq2rdf#readme>

dependencies:
- base >= 4.11 && < 10
- rio >= 0.1.12.0
- cinetv4h
# - rdf4h >= 4 && < 5
- rdf4h >= 4.0.0 && < 4.0.2
- QuickCheck
- quickcheck-instances
- hsparql
- mtl >= 2.2 && < 2.3
- containers
- xsd
- persistent >= 2.8 && < 2.11
- persistent-template
- persistent-sqlite
- esqueleto >= 3 && < 3.4
- time >= 1.8 && < 1.10
- resource-pool >= 0.2 && < 0.3
- conduit >= 1.3 && < 1.4
- aeson >= 1.4 && < 1.5
- text >= 1.2 && < 1.3
- directory >= 1.3 && < 1.4
- zlib >= 0.6 && < 0.7
- bytestring >= 0.9 && < 0.11
- filepath
- regex
- process
- network-uri
- parsec
- hashable
- transformers

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  cq2rdf-exe:
    main:                Main.hs
    source-dirs:         app
    dependencies:
    - cq2rdf
    - optparse-simple

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N

tests:
  cq2rdf-test:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
    - cq2rdf
    - hspec
    - process
    - hspec-expectations

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
